#!/bin/bash

#$ -cwd
#$ -S /bin/bash
#$ -pe orte 320
#$ -q all.q
#$ -V
#$ -N run_3Dclass_177

mpirun relion_refine_mpi --o Class3D/run4 --i particles_noBin_noEdge_MagUpdate.star --particle_diameter 350 --angpix 1.77 --ref emd_2275_scaled_bin4_filt60A_sca_240.mrc --firstiter_cc --ctf --iter 25 --tau2_fudge 3 --K 3 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 1 --memory_per_thread 4






